
name: Docker Image CI

on:
  push:
    branches: [ main ] # Adjust if your default branch is different

permissions:
  contents: read
  packages: write # Required to push to GitHub Packages (ghcr.io)

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Or github.repository_owner for organization repos
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Format: ghcr.io/owner/repo
          tags: |
            type=sha # Tag with commit SHA (e.g., sha-abcdef1)
            latest   # Tag as latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Add build arguments if needed, for example:
          # build-args: |
          #   NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL }}
          # Ensure you have GitHub repository variables (vars) or secrets (secrets) set up if you use them.

